OrdererOrgs:
  - Name: orderer1
    Domain: orderer1
    Template:
      Count: 3

PeerOrgs:
  - Name: org1
    Domain: org1
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: org2
    Domain: org2
    Template:
      Count: 2
    Users:
      Count: 1
