apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: orderer1
  name: kafka0
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: hyperledger
        role: kafka
        org: orderer1
        kafka-id: kafka0
    spec:
      containers:
      - name: kafka0
        image: hyperledger/fabric-kafka:x86_64-1.0.5
        env:
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "1048576"
        - name: KAFKA_REPLICA_FETCH_MAX_BYTES
          value: "1048576"
        - name: KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE
          value: "false"
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_MIN_INSYNC_REPLICAS
          value: "2"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka0
        ports:
         - containerPort: 9092
        volumeMounts:
         - mountPath: /tmp/kafka-logs
           name: kafkalogs
           subPath: kafka0/kafka-logs
      volumes:
         - name: kafkalogs
           persistentVolumeClaim:
               claimName: kafka-shared

---

apiVersion: v1
kind: Service
metadata:
  namespace: orderer1
  name: kafka0
spec:
 selector:
   app: hyperledger
   role: kafka
   kafka-id: kafka0
   org: orderer1
 clusterIP: None
 ports:
   - name: listen-endpoint
     protocol: TCP
     port: 9092

---