apiVersion: v1
kind: Namespace
metadata:
  name: org1
---

apiVersion: v1
kind: Namespace
metadata:
  name: org2

---

apiVersion: v1
kind: Namespace
metadata:
  name: orderer1

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: orderer1-shared
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: orderer1
    name: orderer1-shared
  nfs:
    path: /opt/share/mycluster/resources/crypto-config/ordererOrganizations/orderer1
    server: 172.18.158.121

---

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: org1-shared
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: org1
    name: org1-shared
  nfs:
    path: /opt/share/mycluster/resources/crypto-config/peerOrganizations/org1
    server: 172.18.158.121

---

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: org2-shared
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: org2
    name: org2-shared
  nfs:
    path: /opt/share/mycluster/resources/crypto-config/peerOrganizations/org2
    server: 172.18.158.121

---


apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-shared
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: orderer1
    name: kafka-shared
  nfs:
    path: /opt/share/mycluster/resources/kafka
    server: 172.18.158.121

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-shared
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: orderer1
    name: zookeeper-shared
  nfs:
    path: /opt/share/mycluster/resources/zookeeper
    server: 172.18.158.121

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: orderer1
 name: orderer1-shared
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: org1
 name: org1-shared
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Mi

---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: org2
 name: org2-shared
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Mi

---




apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: orderer1
 name: kafka-shared
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: orderer1
 name: zookeeper-shared
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Mi

---